_output_dir: "/Users/costi/code/ck"
_repo_dir: "/Users/costi/.cookiecutters/cookiecutter-django-wagtail"
_template: git@github.com:ck-tm/cookiecutter-django-wagtail.git
author_name: CK
ci_tool: Github
cloud_provider: None
debug: y
description: Behold My Awesome Project!
domain_name: staging.24h-unsichtbar.at
email: costi.bleotu@gmail.com
frontend_pipeline: Webpack
keep_local_envs_in_vcs: y
mail_service: Mailgun
open_source_license: MIT
postgresql_version: "15"
project_name: IG24
project_slug: ig24
timezone: UTC
use_async: n
use_celery: y
use_docker: y
use_heroku: n
use_mailhog: y
use_pycharm: n
use_sentry: y
use_whitenoise: y
version: 0.1.0
windows: n
